name: RingsOfHell
version: '${project.version}'
main: me.ltommi.ringsofhell.Main
api-version: 1.20
commands:
  dungeon:
    description: dungeon
    usage: /<command>
permissions:
  roh.player:
    description: permission to use player commands
    default: false
  roh.admin:
    description: permission to use admin commands
    default: false
    children:
      roh.player: true
